const Tier = {
  // Enum
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
  BC: 5,
  HISP: 6,
  OTT: 7,
  SAT: 8,
  SYND: 9,
  UW: 10,
  VOD: 11,
}

const Station = {
  PHIL: 'DR. PHIL',
  MAIL: 'The Daily Mail',
  DOCT: 'THE DOCTORS',
  WENDY: 'THE WENDY WILLIAMS SHOW',
  DEPEL: 'De Pelicula',
  ESPUL: 'ESPN University Local',
  DLAT: 'Dish Latino',
  ANT3: 'Antenna 3',
  ESTUD: 'E Studios',
  ACCN: 'ACC Network',
  TELFO: 'Teleformula',
  DISCF: 'Discovery Familia',
  DXD: 'Disney XD',
  BANDA: 'Bandamax TV',
  UNIM: 'UniMas',
  DEPEC: 'De Pelicula Clasico',
  BABYF: 'Baby First',
  BEIN: 'BEin Sports',
  GRIT: 'Grit',
  ESCP: 'ESCAPE',
  CUBMX: 'CubaMax',
  BOUNC: 'Bounce',
  HISTE: 'History Espanol',
  MTV3: 'MTV Tr3s',
  LIFEL: 'Lifetime (Local)',
  TSALV: 'Tele Salvador',
  ATRES: 'Atres Series',
  RVLT: 'Revolt',
  FORO: 'FOROTV',
  MEX22: 'Mexico 22',
  MTVC: 'MTV Classic',
  TVCS: 'TvC Sports',
  TNNK: 'Teen Nick',
  TBSL: 'Turner Broadcast Local',
  TV1: 'TV1',
  DOMVW: 'Dominican View',
  ECUAV: 'Ecuavisa International',
  RCNOV: 'RCN Novelas',
  BBCA: 'BBC America',
  TELEX: 'Tele Xitos',
  ASPR: 'Aspire TV',
  FOXNC: 'Fox News Channel',
  NUESA: 'NuestraTele',
  GALA: 'GALAVISION',
  WGN: 'W G N - Superstation',
  AMC: 'American Movie Classics',
  TVVEN: 'TV Venezuela',
  IFC: 'Independent Film Channel',
  WE: "Women's Entertainment",
  TVL: 'TV Land',
  CBSS: 'CBS Sports',
  COZI: 'COZI-TV',
  DISHH: 'Dish Net Young Adult',
  HALDR: 'Hallmark Drama',
  MSNBC: 'MSNBC',
  AMTV: 'MTV Networks AM',
  USA: 'USA',
  TBS: 'TBS (Turner Broadcast)',
  FUSE: 'FUSE',
  MTV2: 'MTV2',
  VH1L: 'VH1-Local',
  NTN24: 'NTN 24',
  TNT: 'TNT (Turner Network TV)',
  CMT: 'CMT',
  CARAC: 'Caracol International',
  BETHL: 'BET Her Local',
  CWVOD: 'The CW Network',
  KCLRK: 'The Kelly Clarkson Show',
  DISHC: 'Dish Net - Adult Cluster',
  BOOM: 'Boomerang',
  DISHE: 'Dish Net Ent-13',
  UNBC: 'NBC Universo',
  BETH: 'BET Her',
  DISC: 'Discovery Channel',
  DRTVY: 'DirecTV Young Adult',
  TOONL: 'Cartoon Network Local',
  TOON: 'Cartoon Network',
  TELFE: 'Telefe',
  TLC: 'The Learning Channel',
  BET: 'BET - Black Entertainment TV',
  TELEN: 'La Telenovela',
  LOGO: 'Logo',
  AZTEC: 'Azteca-America',
  AEN: 'Arts and Entertainment',
  FXX: 'FXX',
  MULTI: 'Multi Medios',
  VIRO: 'Video Rola',
  TRU: 'Tru TV',
  SYFY: 'SYFY',
  VH1: 'VH1',
  DRTVH: 'DirecTV Hispanic',
  ESTR: 'Estrella-Hispanic',
  HIST: 'The History Channel',
  PARAL: 'Paramount Locals',
  FOXDP: 'Fox Deportes',
  CRIME: 'Crime and Investigation',
  TRAV: 'The Travel Channel',
  CINEL: 'CineLatino',
  DISCE: 'Discovery en Espanol',
  CNTRA: 'CentroAmerica TV',
  PARAN: 'Paramount Network',
  GOLTV: 'GOL TV-Hispanic',
  MTV: 'MTV Networks',
  BETL: 'Black Entertainment Local',
  UNIV: 'UNIVISION',
  WAPAA: 'WAPA America',
  COM: 'Comedy Central',
  MAVTV: 'MAVTV',
  SCANA: 'Super Canal',
  NBALP: 'NBA League Pass',
  POP: 'POP',
  ENT: 'E! Entertainment TV',
  TNTL: 'Turner Network TV Local',
  BRAVL: 'Bravo Local',
  DISF: 'Discovery Family',
  TRUL: 'TRU TV - LOCALS',
  FXML: 'FX Movie Channel Local',
  FRFML: 'FreeForm Locals(formerly ABC',
  ENTL: 'E! Entertainment TV Local',
  TBD: 'TBD Network',
  ADSML: 'Adult Swim Locals',
  INSED: 'Inside Edition',
  MTV2L: 'MTV2 - local',
  BBCAL: 'BBC America Local',
  ION: 'ION',
  GTWBE: 'Game TIme With Boomer Esiason',
  CBS: 'CBS Television',
  CNN: 'CNN-Cable Net News',
  FOXNL: 'Fox News Channel Local',
  DTVE: 'DirecTV Everywhere',
  EXTRA: 'Extra',
  ZMUND: 'Zee Mundo',
  HGTV: 'Home & Garden TV',
  CHILE: 'TV Chile',
  FOODL: 'Food Network (Local)',
  FX: 'FX',
  TELEM: 'Telemundo',
  HALL: 'The Hallmark Channel',
  TLCL: 'TLC Local',
  MTVL: 'MTV Networks Local',
  NBC: 'NBC Television',
  AHOLL: 'ACCESS HOLLYWOOD',
  DISCL: 'The Discovery Channel - Local',
  NUUM: 'Continuum Media',
  DRFS1: 'Direct TV Fox Sports 1',
  DRESP: 'DirecTV ESPN Live Sports',
  ETWK: 'Entertainment Tonight WKND',
  DRNBC: 'Direct TV NBCS',
  ROKU: 'Roku',
  TURNV: 'Turner Entertainment VOD',
  TUBIV: 'Tubi VOD',
  HULU: 'HULU',
  AENV: 'A&E VOD',
  VIACV: 'Viacom VOD',
  DISGV: 'Discovery Go VOD',
  UNOTT: 'Univision OTT',
  SINCL: 'Sinclair Unwired',
  BETV: 'Black Entertainment VOD',
  PLUTV: 'Pluto VOD',
  NBCV: 'NBC Network VOD',
  NAN: 'Nick at Nite',
  NCISO: 'NCIS New Orleans',
  HLN: 'Headline News',
  RIDE: 'Ride TV',
  CBSI: 'CBS Interactive',
  SECN: 'SEC Network',
  SLING: 'Sling',
  FOXSG: 'Fox Sports Go VOD',
  FUBO: 'Fubo',
  CRAKL: 'Crackle',
  ABC: 'ABC Domestic Television (PR)',
  CHPDS: 'Chicago PD strip',
  LOSV: 'LAW&ORDER SVU',
  MLB: 'MLB Network',
  ESP2: 'ESPN2',
  ESPN: 'ESPN',
  FOX: 'FOX Television',
  TENCH: 'The Tennis Channel',
  FEUD: 'FAMILY FEUD',
  ADSM: 'Adult Swim',
  DISHO: 'Dish Net - Live Sports',
  LAWO: 'Law & Order',
}

module.exports = {
  Station,
  Tier,
}
