** How to make it go

1. Install dependencies on the client and server. I'm on Node
   12.16.1, but you should be fine with LTS or later.
2. Run the transform command on the backend to prepare the data to be served

3. Start the server in watch mode with `npm run dev`

4. Start the client in watch mode with `npm run start`

Navigate to http://localhost:3000 to see the frontend

** Known bugs

- Switching between routes/stations too quickly can cause the app to crash. This
  is something I noticed at the end, and did not have much time to investigate.
- File streaming had several bugs in it last I checked, so the default
  configuration for now is running a one-time command that groups the dataset by
  week of airdate, and then by the station that paid for the ad.

- The time-consuming part was the problem of getting the data to the client, and not so
  much creating visual representations of the data. If I could start over I
  would invest time in setting up a database from the beginning, I think that
  would have saved me time in the long run.

** Style

I try to write pointfree code when I can. In my experience with greenroots
projects, this has been an effective way to stay flexible and delay having to
name things until later on. It's been an effective way to avoid getting tied
down to a particular approach early on, but I'm also cognizant of the fact that
not everybody understands it right away -- I would discuss with my team before
making assumptions about what everyone is comfortable with, as every team is different.
