export const initialState = {}

export const TOGGLE_FOCUS = 'UI/TOGGLE_FOCUS'

export const OVERVIEW_SET_PENDING = 'FETCH/OVERVIEW/SET_PENDING'
export const OVERVIEW_SET_ERROR = 'FETCH/OVERVIEW/SET_ERROR'
export const OVERVIEW_SET_DATA = 'FETCH/OVERVIEW/SET_DATA'

export const STATIONMAP_SET_PENDING = 'FETCH/STATIONMAP/SET_PENDING'
export const STATIONMAP_SET_ERROR = 'FETCH/STATIONMAP/SET_ERROR'
export const STATIONMAP_SET_DATA = 'FETCH/STATIONMAP/SET_DATA'
